task1= Task.create!(title:"Legs", complete:false)
task2= Task.create!(title:"Head", complete:false)
task3= Task.create!(title:"Fiction", complete:false)
task4= Task.create!(title:"Nonfiction", complete:false)
task5= Task.create!(title:"Chilly Chill", complete:false)

Goalset.create!(title:"Exercise", target_date:DateTime.now, complete:false, tasks:[task1,task2])
Goalset.create!(title:"Read", target_date:DateTime.now, complete:false, tasks:[task3,task4])
Goalset.create!(title:"Lollygag", target_date:DateTime.now, complete:true, tasks:[task5])
Goalset.create!(title:"Jazzercise", target_date:DateTime.now, complete:false, tasks:[task5])
Goalset.create!(title:"Loaf", target_date:DateTime.now, complete:true, tasks:[task5])